### ISSUE TITLE
Workday/Paycheck Not Recognized

### ISSUE THREAD

**Issue by arnold-c** [redstreet/beancount_reds_importers#37]
Hi Red,

Really liking your Beancount importers, so thanks for publishing them.

I'm trying to use the Workday importer to process everything related to my paycheck in one go, but unfortunately I'm getting a blank result to `bean-identify _config.py workday.xlsx`.

My _config.py looks like this:

```
from unittest import skip
from beancount.ingest.importers.csv import Importer as CSVImporter, Col
from beancount_reds_importers import workday

paycheck_template = {

        'EE Taxes': {
            "Federal Withholding": "Expenses:US:Taxes:Federal"
        }

    }

workday = workday.Importer({'desc': "Work",
    'main_account': 'Income:US:Hooli:Gross-Income',
    'paycheck_template': paycheck_template,
    'currency': 'USD',
})

CONFIG = [
    workday
    ]
```

With a sub-table heading "EE Taxes", and "Federal Withholding" being a row within that table.

I'm sure I'm missing something obvious, but I've been going round in circles so thought I'd ask just in case there was something else going on.

**Comment by redstreet** [comment]
Hello there,
Glad they're useful!

Ah, the Workday importer is the hackiest one of them all, since I only have one example :). `bean-identify` is not identifying your file likely because of one of these lines:
- [Filename should have `_Complete`](https://github.com/redstreet/beancount_reds_importers/blob/a5d7dbf4e87f4a109ec30f12df22ac0a6fe6b297/beancount_reds_importers/workday/__init__.py#L24)
- [Header should contain `- Complete`](https://github.com/redstreet/beancount_reds_importers/blob/a5d7dbf4e87f4a109ec30f12df22ac0a6fe6b297/beancount_reds_importers/workday/__init__.py#L25)

Either or both of those are probably not true for you. So I'd recommend simply copying that workday importer and making your own, and modifying those lines. Let me know if you still run into issues.

**Comment by arnold-c** [comment]
Amazing. Thanks so much for the quick response. Adding "_Complete" to the filename fixed the issue so I'll close the issue

**Comment by redstreet** [comment]
Great! You can set `filename_pattern` in your config to something that matches your file. I should probably document this somewhere.
